cleaned up the directory and added more comments to grep_testing

diff --git a/ed_clone/grep_testing b/ed_clone/grep_testing
--- a/ed_clone/grep_testing
+++ b/ed_clone/grep_testing
@@ -1,19 +1,23 @@
 #!/usr/bin/env zsh
 
+# This script was used to test the functionality of the source file along the way through development
+
 function succ_(){
-  echo "[+] BUILD SUCCEEDED!"
-  echo "[+] Number of non blank lines: $(cat ed_manip.c edder.h |  sed '/^\s*#/d;/^\s*$/d' | wc -l)"
+  # Checking how many lines both source files had
+  echo "[+] BUILD SUCCEEDED!: ($(tail -n1 warning_error_logs.txt))"
+  echo "[+] Number of non blank lines: $(cat grep_.c grepper.h |  sed '/^\s*#/d;/^\s*$/d' | wc -l)"
 }
 
 function err_(){
+  # The build had failed in some way, it gives the output of clang, piped to less and can be searched using vim keybindings
   echo "[-] BUILD FAILED"
   cat warning_error_logs.txt | less
   exit
 }
 
 function testing_with_files_(){
-
-  build_input="ed_manip.c"
+  # this was testing the functionality of ed while stripping out components of the editior itself, making sure its integrity was still intact
+  build_input="grep_.c"
   build_input_name="$build_input:t:r"
 
   echo "[+] Building "$build_input" from source...."
@@ -42,12 +46,15 @@ function testing_with_files_(){
 }
 
 function testing_with_arguments_(){
-  clang -lm -g "ed_manip.c" -o "ed_manip" 2> warning_error_logs.txt && succ_ || err_
-  ./ed_manip "^yes" ./input.txt
-  ./ed_manip "^NO" ./input.txt
+  echo "[+] Building grep from source...."
+  clang -lm -g "grep_.c" -o "grep" 2> warning_error_logs.txt && succ_ || err_
+  echo "[+] Running tests for grep_...."
+  ./grep "^yes" ./input.txt
+  echo "================================"
+  ./grep "^NO" ./input.txt
+  echo "================================"
+  ./grep "\$container" ./input.txt
 }
 
-[[ -z "$@" ]] && exit
-target="$1"
-name="$1:t:r"
 testing_with_arguments_
+rm ./grep
